web:
  image: sb_m1
  ports:
    - "80:80"
  links:
    - mysql
  env_file:
    - env
  volumes:
    - /home/jonathan/dev/magento1-plugin:/var/www/htdocs/plugins/springbot
mysql:
  image: mysql:5.6.23
  env_file:
    - env
